### ISSUE TITLE
Code generation picks the wrong function

### ISSUE THREAD

**Issue by edkelly303** [lue-bird/elm-review-documentation-code-snippet#2]
Hello again! I think I've found a bug:

Here's an excerpt from a code example in the docs for the `record` function in my `Control` module: 

```elm
    myRecordControl =
        record
            (\name age ->
                { name = name
                , age = age
                }
            )
            |> field .name string
            |> field .age int
            |> endRecord
```

Generated code:

```elm
myRecordControl__Control__record_0 =
    Control.record (\name age -> { name = Control.name, age = age })
        |> Control.field .name Control.string
        |> Control.field .age Control.int
        |> Control.endRecord
```

The rule seems to get confused and think that the variable `name` in the anonymous function refers to the top-level definition `name` from the `Control` module, but actually it should refer to the argument supplied to the anonymous function.

**Comment by edkelly303** [comment]
Thinking about this overnight, I guess the problem here is that doc examples implicitly do `import [CurrentModule] exposing (..)`, which means that the `name` variable in the code example is shadowing the top-level `Control.name` function. 

I cant check right now, but if I actually wrote the the `myRecordControl` function in a module that imports (..) from Control, then I guess I'd probably get a shadowing error, or perhaps an ambiguous import error.

(The annoying thing is that in real-world code, I would never import everything from Control - I'd always use the qualified names. So the doc examples arguably teach bad habits...)

But I'm not sure what, if anything, the rule should do here. The invalid code it currently generates in this situation is fair enough, but it is a bit puzzling until you realise what's going on.

**Comment by lue-bird** [comment]
That definitely needs fixing.
I see 2 possible ways to fix the problem
  - let `import CurrentModule exposing (..)` vs `import CurrentModule` be a configuration setting on the rule
      - possible bonus: introduce elm-review errors for attempted shadowing
  - go against what elm would do and shadow all new variables

I prefer the first one, which will also be the most performant, least error prone and most clear for snippet readers. I prefer it so much so that I might only add an "expose everything" option as legacy.

One other way I had rejected previously already is forcing you to define "default imports" for each module you have an expectation mark in. Another I rejected is specifying general rules to create the "default imports" like "only types".

**Comment by edkelly303** [comment]
With the first option, would it be possible to allow the package author to (optionally) add an import statement for the current module at the start of each code snippet?

For example, in my code snippet above, if it started with `import Control exposing (record, field, endRecord, string, int)`, then: 
1. the shadowing problem wouldn't happen; 
2. it would be totally clear to the reader of the docs where the functions come from, and 
3. it would keep the code example uncluttered because it wouldn't need `Control.functionName` everywhere.

If there is no import statement in the code snippet, then it could default to either `import CurrentModule` or `import CurrentModule exposing (..)`, based on the rule's configuration setting.

**Comment by lue-bird** [comment]
>With the first option, would it be possible to allow the package author to (optionally) add an import statement for the current module at the start of each code snippet?

(Obviously) this should then be possible, yes

**Comment by edkelly303** [comment]
Thanks for clarifying! And thanks again for this brilliant rule, it's already made my docs so much better.

**Comment by lue-bird** [comment]
This took some time but now you should also get notified when you forgot to import something.

Thanks for the bug report!

**Comment by edkelly303** [comment]
Amazing! Thank you!
